### PR TITLE
(742) Download "submitted applications" report

### PR DESCRIPTION
**Pull request by edavey**
# "MI user" downloads spreadsheet detailing submitted applications

[Trello 742](https://trello.com/c/GEIpAHHy/742-generate-report-of-applicationsubmitted-events)

# Changes in this PR

A user with the `CAS2_MI` role can now download a spreadsheet of information about submitted applications. 

See 

- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1284 and
- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1294

for information about the download. It features the following columns:

```
- eventId: 63cbe435-768e-43ab-9164-a57784926f91
- applicationId: 6620721f-eba5-4a10-affb-dd3309b04f41
- personCrn: X320741
- personNoms: A1234AI
- referringPrisonCode: LEI
- preferredAreas: Leeds | Bradford
- hdcEligibilityDate: 2023-03-30
- conditionalReleaseDate: 2023-04-29
- submittedOn: 2024-01-03
- submittedBy: POM_USER
```

### MI User's dashboard
mi_user_dashboard

### UI
reports_index_2

### Download
downloaded_file

### Spreadsheet
downloaded_spreadsheet

# Release checklist

## Pre merge checklist

- [ ] Are any changes required to the e2e tests?
- [x] If you've added a new route, have you added a new
  `auditEvent`? - the existing auditing is working: `Sending audit message DOWNLOAD_REPORT ({"name":"submitted-applications"})`
- [ ] Are there environment variables or other infrastructure configuration which needs to be included in this release?
- [ ] Are there any data migrations required. Automatic or manual?
- [x] Does this rely on changes being deployed to the CAS API? - yes relies on https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1284

### CODE REVIEW

**Comment by edavey** [comment]
[Generate report of 'application.submitted' events](https://trello.com/c/GEIpAHHy/742-generate-report-of-applicationsubmitted-events)

**Comment by Harriethw** [comment]
Would it be possible to add a 'tile' to the homepage for users with this role, now there is a real report?

**Comment by edavey** [comment]
> Would it be possible to add a 'tile' to the homepage for users with this role, now there is a real report?

yes, that makes sense, I'll have a go at that...

**Comment by edavey** [comment]
@Harriethw I've added to this PR as follows:

- UI now POSTs "first-class" properties pulled up from `application.data` on submission
- CAS2_MI_USER now sees 'tile' leading to report downloads on dashboard

**Pull request merged**
